### PR TITLE
Upgradeable contract

### PR DESCRIPTION
**Pull request by IpastorSan**
Hi, I have seen in the README that you wanted to add support for Upgradeable contracts. I made changes to the base ERC721A contract without touching base functionality, so it can work as a transparent upgradeable proxy together with the Hardhat-upgrades plugin (I have not tested it with Truffle).

List of changes:
1) Changed imports to Openzepelin contracts-upgradeable set
2) Moved the order of inheritance to adapt to linearization requirements
3) Made explicit some overrides in functions.
4) Changed constructor for initializer.

I have tested on Polygon Mumbai testnet following the patterns in this tutorial: https://docs.openzeppelin.com/learn/upgrading-smart-contracts.
I can provide the scripts for deployment and upgrade if needed. 

Admin contract: 0x5c8E6fd2878aB75eCE1B8436353fd7963e44DD38
Proxy contract: 0x7626F47e7Ae07035945384d2461bdA2c0DcEE96c
Latest implementation contract: 0xFB853708acF5f30a68E151CA946E8f533494a1e6

I have only tested that it can get deployed and upgraded, I have not checked if it passes the existing test suite but can do so if needed, I wanted to get the ball rolling.

### CODE REVIEW

**Comment by Vectorized** [comment]
Thank you for your submission.

We have a transpiler based implementation in the works.

https://github.com/Vectorized/ERC721A-Transpiler
https://github.com/Vectorized/ERC721A-Upgradeable

We will credit you on Twitter for the next release.

**Comment by IpastorSan** [comment]
Thats cool, let me know if there is something that I can do to contribute!

**Comment by Vectorized** [comment]
Just in case:

If you have time, help check if the stuff generated by the transpiler at 
https://github.com/Vectorized/ERC721A-Upgradeable are actually deployable and upgradable on a testnet.

Thanks!

**Comment by IpastorSan** [comment]
Hi, I just deployed and upgraded successfully both in Rinkeby and Polygon Mumbai using the hardhat upgrades plugin. It does not seem to raise any problem. 

I am leaving here the repo that I made for the test, you can check the .openzeppelin folder there.
https://github.com/IpastorSan/ERC721A-Upgradeable-transpiler-test

I hope it is useful, best!

**Pull request closed without merging**
