### PR TITLE
Create SimpleERC721A.sol

### PR DESCRIPTION
**Pull request by 0xJacobean**
This is a super straightforward implementation of the ERC721A with the basic set of features I think a 10K project would need. Thanks!

### CODE REVIEW

**Comment by AndreiD** [comment]
good idea. add merkle root whitelist and it's good to go ;)

**Comment by cygaar** [comment]
We want to keep this repo for just ERC721A - this seems to be more of an implementation, and we don't necessarily need that.

**Comment by AndreiD** [comment]
this could be in some folder like "example". I think it's a good idea for new developers to see how this library gets integrated.

**Comment by AndreiD** [comment]
ah, now I see you wrote in the README a tutorial. nevermind then

**Pull request closed without merging**
