### PR TITLE
Add Candy Chain to projects.md

### PR DESCRIPTION
**Pull request by kyokosdream**
Adds Candy Chain to the projects list. Need to confirm with authors if Mumbaiscan url is okay with them. Can omit until we publish an Etherscan mainnet version if they'd like.

### CODE REVIEW

**Review by cygaar — APPROVED** [review]

**Comment by cygaar** [comment]
Actually can you add this when the etherscan is available?

**Review by cygaar — CHANGES_REQUESTED** [review]
.

**Comment by kyokosdream** [comment]
Yes, we will verify on Etherscan today. A user caught an error in one of our require checks so we are just running some tests to make sure it's good to go before we spend currency on deployment and verification.

**Comment by kyokosdream** [comment]
@cygaar Added Etherscan address

**Pull request merged**
