### PR TITLE
added and tested OpenZeppelin's compatible upgradable version

### PR DESCRIPTION
**Pull request by naomsa**
**ERC721Upgradable**
- __ERC721A_init() instead of constructor()
- Uses @openzeppelin/contracts-upgradeable code
- Tested with @openzeppelin/hardhat-upgrades

### CODE REVIEW

**Comment by tpae** [comment]
@cygaar, I think this PR is cleaner than #4. However, I can see a lot of the work has been done on it for #4 and it was created before this. What is the process for merging PRs in this case?

**Comment by tpae** [comment]
@naomsa, is the `ERC721AUpgradeable.sol` up to date with what is on `main` for `ERC721A.sol`?

**Comment by naomsa** [comment]
@tpae it's not up to date, so if someone want to make it so, we just need to merge and make the necessary updates

**Comment by martincik** [comment]
Any updates on when this might be in the `main`?

**Comment by KfishNFT** [comment]
Updated with the latest changes from main on a PR [to ](https://github.com/naomsa/ERC721A/pull/2) @naomsa

**Comment by naomsa** [comment]
guys, we need this asap

**Comment by AboldUSER** [comment]
For this OZ compatible version, just curious as to why it doesn't have a __gap at the end, like other OZ upgradeable functions?

**Pull request closed without merging**
