### PR TITLE
Add coverage lib to hardhat config + add yarn command

### PR DESCRIPTION
**Pull request by 0xkerning**
One of the TODOs in the README is to increase test coverage. 

This PR adds the `solidity-coverage` tool (whose import is gated behind an env var) and a `yarn` command to run coverage.

Initial report:

```
--------------------------------------------|----------|----------|----------|----------|----------------|
File                                        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------------------|----------|----------|----------|----------|----------------|
 contracts/                                 |    85.94 |    79.41 |    81.82 |    85.53 |                |
  ERC721A.sol                               |    85.94 |    79.41 |    81.82 |    85.53 |... 252,328,564 |
 contracts/extensions/                      |      100 |       90 |      100 |      100 |                |
  ERC721ABurnable.sol                       |      100 |       50 |      100 |      100 |                |
  ERC721AOwnersExplicit.sol                 |      100 |      100 |      100 |      100 |                |
 contracts/mocks/                           |     87.1 |      100 |    89.47 |     87.1 |                |
  ERC721ABurnableMock.sol                   |       75 |      100 |       80 |       75 |             20 |
  ERC721ABurnableOwnersExplicitMock.sol     |       75 |      100 |       80 |       75 |             13 |
  ERC721ABurnableStartTokenIdMock.sol       |      100 |      100 |      100 |      100 |                |
  ERC721AGasReporterMock.sol                |      100 |      100 |      100 |      100 |                |
  ERC721AMock.sol                           |    77.78 |      100 |       80 |    77.78 |          28,44 |
  ERC721AOwnersExplicitMock.sol             |      100 |      100 |      100 |      100 |                |
  ERC721AOwnersExplicitStartTokenIdMock.sol |      100 |      100 |      100 |      100 |                |
  ERC721AStartTokenIdMock.sol               |      100 |      100 |      100 |      100 |                |
  ERC721ReceiverMock.sol                    |      100 |      100 |      100 |      100 |                |
  StartTokenIdHelper.sol                    |      100 |      100 |      100 |      100 |                |
--------------------------------------------|----------|----------|----------|----------|----------------|
All files                                   |    87.62 |    81.82 |     86.3 |    87.29 |                |
--------------------------------------------|----------|----------|----------|----------|----------------|

```

### CODE REVIEW

**Comment by cygaar** [comment]
Awesome!

**Comment by cygaar** [comment]
@0xkerning can you get CI to pass?

**Comment by davidlee1435** [comment]
@cygaar confirmed that `npm ci` runs locally!

**Comment by 0xkerning** [comment]
done!

**Pull request merged**
